name: Deploy Astro a GitHub Pages

on:
  push:
    branches: ["main"] # O "master" si tu rama principal se llama así

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de tu código
        uses: actions/checkout@v4
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependencias
        run: npm install
      - name: Compilar el sitio de Astro
        run: npm run build
      - name: Subir los archivos generados
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4